<?xml version="1.0" encoding="UTF-8"?>
<testsuite time='1.014095' skipped='0' failures='0' errors='0' name="RunTimedOutTest" assertions='9' tests='4' timestamp="2024-10-29T09:02:01+00:00">
  <testcase time='0.004758' file="test/id58_test_base.rb" name="test_\nid=&#39;c7Ag55&#39;\nos=Alpine\n&#39;timeout in wait_thread.value results in timed_out status and any captured stdout/stderr are not part of run_cyber_dojo_sh result&#39;" assertions='4'>
  </testcase>
  <testcase time='1.006155' file="test/id58_test_base.rb" name="test_\nid=&#39;c7Ag56&#39;\nos=Alpine\n&#39;\n  in capture3_with_timeout()\n  when process.spawn() fails to respond within the timeout period\n  thats also a timeout\n  and no process.detch() call is made\n  and no process.kill() call is made\n  &#39;" assertions='1'>
  </testcase>
  <testcase time='0.001971' file="test/id58_test_base.rb" name="test_\nid=&#39;c7Ag57&#39;\nos=Alpine\n&#39;in capture3_with_timeout() when process.kill(:TERM,-pid) completes then wait_thread.join() returns non nil and the process.kill(:KILL, -pid) call is not made&#39;" assertions='2'>
  </testcase>
  <testcase time='0.001212' file="test/id58_test_base.rb" name="test_\nid=&#39;c7Ag58&#39;\nos=Alpine\n&#39;in capture3_with_timeout() when there is no timeout&#39;" assertions='2'>
  </testcase>
</testsuite>
